# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Socle < Formula
  desc "CLI tool for managing stacked Git branches"
  homepage "https://github.com/benekuehn/socle"
  version "0.1.0-alpha.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/benekuehn/socle/releases/download/v0.1.0-alpha.5/socle_0.1.0-alpha.5_darwin_amd64.tar.gz"
    sha256 "81487d594443e036f457c908ac0e49b1b030037a67451446f23cd894a578ee41"

    def install
      bin.install "so"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/benekuehn/socle/releases/download/v0.1.0-alpha.5/socle_0.1.0-alpha.5_darwin_arm64.tar.gz"
    sha256 "c94409bd3134c7865dc9c3a7d3771651a224a9e7ee21cb101a11ce924c809479"

    def install
      bin.install "so"
    end
  end
end
