# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Socle < Formula
  desc "CLI tool for managing stacked Git branches"
  homepage "https://github.com/benekuehn/socle"
  version "0.1.0-alpha.6"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/benekuehn/socle/releases/download/v0.1.0-alpha.6/socle_0.1.0-alpha.6_darwin_amd64.tar.gz"
    sha256 "715d4871a90676b64fa6cc9d67ef470f6845ba0470b8a49ae477996d0e4f2655"

    def install
      bin.install "so"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/benekuehn/socle/releases/download/v0.1.0-alpha.6/socle_0.1.0-alpha.6_darwin_arm64.tar.gz"
    sha256 "449b2281a2761cb6a13d3f24ae7d1a8c2fd5d1fcc21d3a60adb9deb25731ac9d"

    def install
      bin.install "so"
    end
  end
end
